node {

    /* =========================
       Job Configuration
       ========================= */
    properties([
        parameters([
            choice(
                name: 'ENV',
                choices: ['dev', 'uat', 'prod'],
                description: 'Select environment'
            )
        ]),
        disableConcurrentBuilds()
    ])

    /* =========================
       Checkout Source Code
       ========================= */
    stage('Checkout') {
        git branch: 'main',
            url: 'https://github.com/MANOJSP2000/terraform-task7.git'
    }

    /* =========================
       Terraform Execution
       ========================= */
    stage('Terraform with Lock') {

        // Environment-level concurrency control
        lock("terraform-${params.ENV}") {

            stage('Terraform Init') {
                sh """
                terraform init \
                  -backend-config=envs/${params.ENV}/backend.tf \
                  -reconfigure
                """
            }

            stage('Terraform Plan') {
                sh 'terraform plan'
            }

            stage('Terraform Apply') {
                sh 'terraform apply -auto-approve'
            }
        }
    }
}
