node {

    properties([
        parameters([
            choice(
                name: 'ENV',
                choices: ['dev', 'uat', 'prod'],
                description: 'Select environment'
            )
        ]),
        disableConcurrentBuilds()
    ])

    stage('Checkout') {
        git branch: 'main',
            url: 'https://github.com/MANOJSP2000/terraform-task7.git'
    }

    stage('Terraform with Lock') {
        lock("terraform-${params.ENV}") {

            stage('Terraform Init') {
                sh """
                cd terraform
                terraform init \
                  -backend-config=../envs/${params.ENV}/backend.tf \
                  -reconfigure
                """
            }

            stage('Terraform Plan') {
                sh "cd terraform && terraform plan"
            }

            stage('Terraform Apply') {
                sh "cd terraform && terraform apply -auto-approve"
            }
        }
    }
}
